name: data_medix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  simple_gradient_text: 1.3.0
  gradient_borders: ^1.0.1
  flutter_svg: ^2.0.17
  markdown: ^7.3.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  toggle_switch: ^2.3.0
  shared_preferences: ^2.5.2
  visibility_detector: ^0.4.0+2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_markdown: ^0.7.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
  - lib/assets/logo.jpg